### ISSUE TITLE
source maps not being generated since 0.5.0

### ISSUE THREAD

**Issue by akkumar** [feldci/vscode-plugin-dartsass#28]
source maps are not getting generated since 0.5.0

**Comment by akkumar** [comment]
v0.5.5 released that generates source maps as well. 

@lekoala - fyi .

**Comment by ImSeaWorld** [comment]
All's well on windows.

**Comment by akkumar** [comment]
Thanks, @ImSeaWorld . 

Can you also hel pconfirm that sourcemaps are indeed correct for what you see as well ?

**Comment by lekoala** [comment]
@akkumar yes all good, both compile on save and watchers are working fine and consistently.

**Comment by akkumar** [comment]
Thanks, @lekoala .

And the source maps are correct too ( especially the one generated from the watcher .min.css.map specifically )

**Comment by lekoala** [comment]
@akkumar yes, they are correct but I think it's missing the  /*# sourceMappingURL={myfile}.min.css.map */ at the end of the min file when using the watcher

on compile on saved there is a sourcemapping but the value is incorrect
/*# sourceMappingURL=to.css.map */
to.css.map should be the name of the file

**Comment by akkumar** [comment]
Ok - Good points. I will see what could be happening here to debug this further. 

But I assume this may not be a showstopper and not until a couple of days before getting back to the same.

**Comment by akkumar** [comment]
> `/*# sourceMappingURL=to.css.map */`

Thanks for pointing out this bug. This definitely seems wrong. 

0.5.7 has been rolled out to fix this one.

**Comment by akkumar** [comment]
> but I think it's missing the /*# sourceMappingURL={myfile}.min.css.map */ at the end of the min file when using the watcher

@lekoala - curious how big of a deal breaker would this be ? if not specified ( as it happens today ) will it be automatically inferred to be "{myfile}.min.css.map" so we can ignore this altogether. 

let me know your thoughts and suggestions here.

**Comment by lekoala** [comment]
@akkumar I don't think browser automatically infer existence of map files (not in chrome on my projects, anyway). It's not really a deal breaker though, because if I really want to use map files, I would probably not use the minified file in the first place. But it makes the .min.css.map file kind of irrelevant

**Comment by akkumar** [comment]
Thanks for helping with the explanation. Let me see if I can add a fix by end of week though for the sake of consistency.

**Comment by akkumar** [comment]
> I don't think browser automatically infer existence of map files (not in chrome on my projects, anyway). 

So , v0.5.9 of the plugin rolled out that should contain the comment 
`/*# sourceMappingURL=main.min.css.map */`

at the end of the minified css file.  FYI .

**Comment by akkumar** [comment]
@lekoala - does the latest version of the plugin address the comment issue ? feel free to let me know if otherwise.

**Comment by lekoala** [comment]
@akkumar yes it does ! I really like the workflow now with how the watchers work transparently it's really convenient.

**Comment by akkumar** [comment]
Thanks, @lekoala . Good to know that this plugin is helpful and convenient. I am closing this issue for now.
