### ISSUE TITLE
Page starts to flicker repeatedly after turning on the watcher and making one edit

### ISSUE THREAD

**Issue by jakubdonovan** [feldci/vscode-plugin-dartsass#30]
There's a bug causing the page to flicker without end after the watcher is turned on and one edit is made.

**Comment by akkumar** [comment]
Behind the scenes, this plugin just delegates the watcher functionality to `sass --watch input:output` cmd. 

So - if there is flickering in the page, could this be a factor/property/setting of the web server used to host the page(s) ? Which web server are you using to host this ?

**Comment by jakubdonovan** [comment]
> Behind the scenes, this plugin just delegates the watcher functionality to `sass --watch input:output` cmd.
> 
> So - if there is flickering in the page, could this be a factor/property/setting of the web server used to host the page(s) ? Which web server are you using to host this ?


Yes, I thought that to be the case, and I did some of my own testing.
I'm hosting the page locally and using visual studio code's live server extension to view the page as I make it. 

I'm certain that my sass is installed correctly, and if I CD into my working folder and execute sass --watch style.sass style.css  the code updates just fine, and there is no flicketing problem. The problems seems to only occur when I try to watch through your extension, and in every browser.

**Comment by akkumar** [comment]
> using visual studio code's live server extension 

> sure that the page flickering is due to endless repeated reload of the page.

I would assume the issue is more to do with live server than with this extension ? 

This extension `writes` only the source file is changed but not otherwise.

**Comment by jakubdonovan** [comment]
> > using visual studio code's live server extension
> 
> > sure that the page flickering is due to endless repeated reload of the page.
> 
> I would assume the issue is more to do with live server extension than with this extension ?
> 
> This extension `writes` only the source file is changed but not otherwise.

But the extension works just fine as long as watch is not activated through your extension. Are you able to replicate the problem?

**Comment by akkumar** [comment]
couple of things to help me reproduce the same . 

I) Is `dartsass.disableMinifiedGeneration` set for this extension ? 

2) Is there a `dartsass.targetDirectory` set for the extension ? 

Any specific settings for `Live Server Extension` that I must be aware of to help reproduce the same ?

**Comment by jakubdonovan** [comment]
**Here's the extension:**
![Screenshot 2020-03-01 at 10 55 57](https://user-images.githubusercontent.com/16073448/75624325-4138d400-5bab-11ea-9afe-d802b89b5572.png)

**Dartsass: Sass Bin Path:**
![Screenshot 2020-03-01 at 10 56 56](https://user-images.githubusercontent.com/16073448/75624343-675e7400-5bab-11ea-9092-a83009322ce8.png)

**dartsass.disableMinifiedGeneration**
![Screenshot 2020-03-01 at 10 58 42](https://user-images.githubusercontent.com/16073448/75624404-b60c0e00-5bab-11ea-8942-975489310137.png)

**dartsass.targetDirectory** 
![Screenshot 2020-03-01 at 10 59 41](https://user-images.githubusercontent.com/16073448/75624412-c45a2a00-5bab-11ea-928c-0a8f5a725ae2.png)

**Comment by akkumar** [comment]
Can you try to set `dartsass.disableMinifiedFileGeneration` to be true 
and see if the flickering goes away ? 

There is a logic in this extension where it listens to the .css files that got changed and generates the minified files with .min.css extension. 

It is possible that the documentRoot as per the "Live Server" extension contains some css files that get changed ?

**Comment by jakubdonovan** [comment]
Didn't make a difference. Here's a video demonstration 
https://youtu.be/nKBbB8nRXRY

**Comment by jakubdonovan** [comment]
> Can you try to set `dartsass.disableMinifiedFileGeneration` to be true
> and see if the flickering goes away ?
> 
> There is a logic in this extension where it listens to a directory for any changes to .css files and generates the minified files with .min.css extension.
> 
> It is possible that the documentRoot as per the "Live Server" extension contains some css files that get changed ?

Didn't make a difference.
Here's a video demonstration https://youtu.be/nKBbB8nRXRY

Did that give you any ideas?

**Comment by akkumar** [comment]
thanks for helping with the video. 

When using the "Live Server" extension, what is the documentRoot used by the same ? Any other setting ( in .vscode/settings.json ) that I can use to understand more about the setting of "live server" extension

**Comment by jakubdonovan** [comment]
> thanks for helping with the video.
> 
> When using the "Live Server" extension, what is the documentRoot used by the same ? Any other setting ( in .vscode/settings.json ) that I can use to understand more about the setting of "live server" extension

It reads the html and css file from the project directory (same directory as the sass extension)

![Screenshot 2020-03-02 at 08 43 11](https://user-images.githubusercontent.com/16073448/75659470-f3cb6e00-5c61-11ea-8fa9-7d7f4123e75b.png)

![Screenshot 2020-03-02 at 08 44 28](https://user-images.githubusercontent.com/16073448/75659568-18274a80-5c62-11ea-97fa-c8b0ad3046c3.png)


Here are the settings for relevant extensions:
![Screenshot 2020-03-02 at 08 40 57](https://user-images.githubusercontent.com/16073448/75659339-b666e080-5c61-11ea-89e7-beebc2683351.png)
![Screenshot 2020-03-02 at 08 41 10](https://user-images.githubusercontent.com/16073448/75659345-b961d100-5c61-11ea-9458-31b30f64cba2.png)

**Comment by akkumar** [comment]
Thanks for the detailed screenshots. 

I am going to take a day or so to investigate this better and come back with what is happening / a fix.

**Comment by jakubdonovan** [comment]
> Thanks for the detailed screenshots.
> 
> I am going to take a day or so to investigate this better and come back with what is happening / a fix.

Sounds good. Let me know if you need me to do anything. We could even hop on teamviewer or anydesk which would allow you to do your checks on my end.

**Comment by akkumar** [comment]
So - I had rolled out a first bugfix that should prevent the flickering occurring when `dartsass.disableMinifiedFileGeneration` is set to true. 

I am in the middle of something else at the moment that I will have time later tomorrow to get back to this and reproduce / address the fix.

**Comment by jakubdonovan** [comment]
> So - I had rolled out a first bugfix release of this plugin v0.5.13 - that should prevent the flickering occurring when `dartsass.disableMinifiedFileGeneration` is set to true.
> 
> I am in the middle of something else at the moment that I will have time later tomorrow to get back to this and reproduce / address the fix.

The update seems to have made the flickering more violent. 
https://youtu.be/VtWUPvX90tM

**Comment by akkumar** [comment]
So , I was trying to reproduce the problem mentioned.

But , I was not able to reproduce the flickering though in my local setup.   When I setup a "sass watcher" and then change a scss file, the change gets reflected in the IDE right away. 

sass compiler 1.26.2 . 

Help -> About -> indicates the following. 

`
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-40-generic
`

I launched the cmd - "Live Server: Open With Live Server" and chose the index.html that was referring the css files inside. 

So - far not able to reproduce the same.

Anything else that possibly differs between the two. 

Instead of live server, if you launch the page externally in a browser window ( ignoring the "Live Server" extension) , does the flickering happen still ? 

Because if the flickering is not happening in the browser, then that would mean the flickering is an issue with "Live Server" extension rather than this one.

**Comment by akkumar** [comment]
So  I have made a newer release - v0.5.14 . 

While this may not necessarily fix the given issue, you can help with the following. 

1) Turn `dartsass.debug` to be true. 

2) When you see the flickering - is there anything in the output of plugin (Output -> "DartJS Sass" ) that you see ? 

This will help to debug the source of the flickering. 

Appreciate your help in the same.

**Comment by jakubdonovan** [comment]
> So I have made a newer release - v0.5.14 .
> 
> While this may not necessarily fix the given issue, you can help with the following.
> 
>     1. Turn `dartsass.debug` to be true.
> 
>     2. When you see the flickering - is there anything in the output of plugin (Output -> "DartJS Sass" ) that you see ?
> 
> 
> This will help to debug the source of the flickering.
> 
> Appreciate your help in the same.

Sorry about the late response. This is the output:

Extension "dartsass" activated now!
INFO: Configuration reloaded with {"sassBinPath":"/usr/local/Cellar/sass/1.26.1/bin/sass","includePath":[],"disableMinifiedFileGeneration":true,"disableSourceMap":true,"sourceEncoding":"utf-8","nodeExePath":"node.exe","debug":false,"disableCompileOnSave":true,"pauseInterval":3,"enableStartWithUnderscores":false,"disableAutoPrefixer":true,"autoPrefixBrowsersList":["> 1%","last 2 versions"],"targetDirectory":"","watchDirectories":[],"minCSSExtension":".min.css"} and projectRoot /Users/jakubdonovan/Documents/learning_coding/CodeInstitute
Warning: Unhandled change in workspacefolder event [object Object]
INFO: Configuration reloaded with {"sassBinPath":"/usr/local/Cellar/sass/1.26.1/bin/sass","includePath":[],"disableMinifiedFileGeneration":true,"disableSourceMap":true,"sourceEncoding":"utf-8","nodeExePath":"node.exe","debug":false,"disableCompileOnSave":true,"pauseInterval":3,"enableStartWithUnderscores":false,"disableAutoPrefixer":true,"autoPrefixBrowsersList":["> 1%","last 2 versions"],"targetDirectory":"","watchDirectories":["/Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css"],"minCSSExtension":".min.css"} and projectRoot /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours
INFO: Watching /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css by /usr/local/Cellar/sass/1.26.1/bin/sass.
INFO: RunDetached: Cwd: /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours. Exec: ../../../../../../usr/local/Cellar/sass/1.26.1/bin/sass --no-source-map  --watch  static/css:static/css
INFO: Detached process /usr/local/Cellar/sass/1.26.1/bin/sass launched with pid 94725
INFO: Configuration reloaded with {"sassBinPath":"/usr/local/Cellar/sass/1.26.1/bin/sass","includePath":[],"disableMinifiedFileGeneration":true,"disableSourceMap":true,"sourceEncoding":"utf-8","nodeExePath":"node.exe","debug":true,"disableCompileOnSave":true,"pauseInterval":3,"enableStartWithUnderscores":false,"disableAutoPrefixer":true,"autoPrefixBrowsersList":["> 1%","last 2 versions"],"targetDirectory":"","watchDirectories":["/Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css"],"minCSSExtension":".min.css"} and projectRoot 
DEBUG: Unwatching /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css with pid 94725
INFO: Watching /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css by /usr/local/Cellar/sass/1.26.1/bin/sass.
INFO: RunDetached: Cwd: . Exec: usr/local/Cellar/sass/1.26.1/bin/sass --no-source-map  --watch  Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css:Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css
INFO: Detached process /usr/local/Cellar/sass/1.26.1/bin/sass launched with pid 94753
INFO: ******************* 1 watchers in memento begin *********
INFO: /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css
INFO: ******************* 1 watchers *********
INFO: ******************* 1 sass watcher processes begin *********
INFO: /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css -> 94753 ( pid )
INFO: ******************* 1 sass watcher processes *********

**Comment by akkumar** [comment]
So  - can you help with the following.

1) Edit and save a scss file, that is present under a directory being watched . 

2) Is there any recurring log that appears in the console log of "DartJS Sass" , something along the lines of - 

```File changed .. 
..
..
```

Is there some kind of repeated information appearing endlessly in the log  ( so we can possibly trace that back to the flickering associated with some files getting changed ).

**Comment by jakubdonovan** [comment]
> So - can you help with the following.
> 
>     1. Edit and save a scss file, that is present under a directory being watched .
> 
>     2. Is there any recurring log that appears in the console log of "DartJS Sass" , something along the lines of -
> 
> 
> ```
> ..
> ..
> ```
> 
> Is there some kind of repeated information appearing endlessly in the log ( so we can possibly trace that back to the flickering associated with some files getting changed ).

I'm having some kind of error today when there is always an active watcher, even when no files are being watched. I've reinstalled the extension and disabled/enabled it a couple times but it doesn't fix the problem.  Here is the output before i even clicked watch:

Extension "dartsass" activated now!
INFO: Configuration reloaded with {"sassBinPath":"/usr/local/Cellar/sass/1.26.1/bin/sass","includePath":[],"disableMinifiedFileGeneration":true,"disableSourceMap":true,"sourceEncoding":"utf-8","nodeExePath":"node.exe","debug":true,"disableCompileOnSave":true,"pauseInterval":3,"enableStartWithUnderscores":false,"disableAutoPrefixer":true,"autoPrefixBrowsersList":["> 1%","last 2 versions"],"targetDirectory":"","watchDirectories":["/Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css"],"minCSSExtension":".min.css"} and projectRoot /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours
INFO: Watching /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css by /usr/local/Cellar/sass/1.26.1/bin/sass.
INFO: RunDetached: Cwd: /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours. Exec: ../../../../../../usr/local/Cellar/sass/1.26.1/bin/sass --no-source-map  --watch  static/css:static/css
INFO: Detached process /usr/local/Cellar/sass/1.26.1/bin/sass launched with pid 96548
INFO: ******************* 1 watchers in memento begin *********
INFO: /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css
INFO: ******************* 1 watchers *********
INFO: ******************* 1 sass watcher processes begin *********
INFO: /Users/jakubdonovan/Documents/learning_coding/Web-Development/Natuours/static/css -> 96548 ( pid )
INFO: ******************* 1 sass watcher processes *********


Any idea what's up?

**Comment by jakubdonovan** [comment]
> So - can you help with the following.
> 
>     1. Edit and save a scss file, that is present under a directory being watched .
> 
>     2. Is there any recurring log that appears in the console log of "DartJS Sass" , something along the lines of -
> 
> 
> ```
> ..
> ..
> ```
> 
> Is there some kind of repeated information appearing endlessly in the log ( so we can possibly trace that back to the flickering associated with some files getting changed ).

You mean you want me to try watching a scss file instead of a sass file?

**Comment by akkumar** [comment]
No - I meant sass files only. You can try repeating this experiment with scs files also. 

What I meant is and what I am looking for is somekind of repeated log statements in the plugin console log to see if there is any kind of loop that is going on , to cause the flickering. 

So far from the logs ,  I don't see one and that makes it harder for me to figure out what is going on. 

Also - I have only added enough debugging statements with the update and not actually the fix since at this point , I don;'t know what is going on (other than possibly a conflict with "Live Server" plugin that also watches for .css files and does some funky stuff ).

**Comment by jakubdonovan** [comment]
> No - I meant sass files only. You can try repeating this experiment with scs files also.
> 
> What I meant is and what I am looking for is somekind of repeated log statements in the plugin console log to see if there is any kind of loop that is going on , to cause the flickering.
> 
> So far from the logs , I don't see one and that makes it harder for me to figure out what is going on.
> 
> Also - I have only added enough debugging statements with the update and not actually the fix since at this point , I don;'t know what is going on (other than possibly a conflict with "Live Server" plugin that also watches for .css files and does some funky stuff ).

Okay. I just disabled the live server extension and ran the index.html file in browser.  I presser watch sass and the flickering is gone. Only issue is, I have to refresh the page every time I want to see my changed take place, whereas live server takes care of all of that for you and automatically refreshes the page everytime a change in css is made.

**Comment by akkumar** [comment]
> This confirms that there is a conflict between the two extensions.

I have installed the live server extension too myself ( on ubuntu linux ) . I have tried to reproduce the same issue that you were mentioning . 

I am not able to able to reproduce that issue on Linux. 

I assume you are running on a mac based on previous comments. So it is possible that the file watcher we are employing using `chokidar` has some quirks on mac os.

> Only issue is, I have to refresh the page every time I want to see my changes take place, whereas live server takes care of all of that for you and automatically refreshes the page everytime a change in css is made.

I can understand the pain of that. But then as we have seen there is nothing i can do at this point since both this plugin and Live Server extension seems to watch for .css files and it seems the Live Server extension does some interesting stuff that I am unable to understand and/or outside the scope of development.

May be it brings an interesting feature to integrate watchers and our own live server , but that is probably for sometime to ponder over. not going to look into the same immediately.

**Comment by jakubdonovan** [comment]
> > This confirms that there is a conflict between the two extensions.
> 
> I have installed the live server extension too myself ( on ubuntu linux ) . I have tried to reproduce the same issue that you were mentioning .
> 
> I am not able to able to reproduce that issue on Linux.
> 
> I assume you are running on a mac based on previous comments. So it is possible that the file watcher we are employing using `chokidar` has some quirks on mac os.
> 
> > Only issue is, I have to refresh the page every time I want to see my changes take place, whereas live server takes care of all of that for you and automatically refreshes the page everytime a change in css is made.
> 
> I can understand the pain of that. But then as we have seen there is nothing i can do at this point since both this plugin and Live Server extension seems to watch for .css files and it seems the Live Server extension does some interesting stuff that I am unable to understand and/or outside the scope of development.
> 
> May be it brings an interesting feature to integrate watchers and roll out our own live server , but that is probably for sometime to ponder over. not going to look into the same immediately.

I mean, there must be a solution because Live Sass Compiler works just fine with Live Sass Compiler
![Screenshot 2020-03-09 at 15 11 39](https://user-images.githubusercontent.com/16073448/76228154-4257aa00-6218-11ea-8a3a-1cf43285ca48.png)

**Comment by akkumar** [comment]
>  because Live Sass Compiler works just fine with with VSC live server.

I guess you meant the extension - Live Server , and not necessarily by the vsc team exposed as an API or similar. 

Also , live Sass Compiler seems to be developed by the same plugin author as that of " Live Server". 

This bug probably would probably be with the "Live Server" extension and see what can be done there. Nothing we can do here to fix that error , I guess.
