### ISSUE TITLE
Add Compile All Files command

### ISSUE THREAD

**Issue by duongdominhchau** [feldci/vscode-plugin-dartsass#31]
I generally don't include generated files in my Git repo, and it means everytime I clone my repo, I will have to recompile all my `.scss` files. I know that I can write a shell script to compile them myself, but it requires another compiler installed.

Currently there is a command named Compiler Current File, but that's the only compile command. Can you add a command to compile all files to `.css` so that I don't need to open every `.scss` files and pressing **Ctrl+S**? Thank you.

**Comment by akkumar** [comment]
So - we have a command called - "DartSass :Watch Directory" as a menu item that appears in every folder. 

You can choose the top-level folder where the .scss files are present and that will start the watcher and that will compile all the .scss files under the same in one go ( without needing to open every file and compiling them). 

Of course, you would need `dartsass.sassBinPath` to be set for that to be working. Please refer documentation in README.md or the properties page in plugin regarding the same. 

Let me know if that works.

**Comment by duongdominhchau** [comment]
For some unknown reasons it doesn't work. VS Code (both `code` from Arch official repo and `vscodium-bin` from AUR) reported
> Relaunch failed: /home/chau/scf/scss - Detached process /usr/bin/sass did not launch correctly. pid is null / undefined - undefined

The path I used is `/usr/bin/sass`, I installed this from AUR (package name `dart-sass`). Running `sass --watch scss:dist/css` manually works, but right-clicking and select watch in VS Code doesn't.

As I have written above, I saw this extension already have a compiler, so I think there may be a way to do this without relying on external tool. Maybe I should have a look at the source code.

**Comment by akkumar** [comment]
It seems like sass did not launch correctly. 

You can install sass locally though. 

`npm install sass@1.26.3`

And then set `sassBinPath` to be `node_modules/.bin/sass` . 

Let me know if that works. 

> I saw this extension already have a compiler, so I think there may be a way to do this without relying on external tool.

Yup. although the sass api does not expose the watch functionality as it stands today and hence the need for an external compiler. See #19 for background on the same.

**Comment by duongdominhchau** [comment]
Thank you for that information, installing `sass` locally works.

**Comment by akkumar** [comment]
Good to know that. 

> The path I used is /usr/bin/sass, I installed this from AUR (package name dart-sass). Running sass --watch scss:dist/css manually works, but right-clicking and select watch in VS Code doesn't.

I am no ArchLinux expert, but you can install sass globally through npm ( as opposed to the distro repository since the distro software might be quite old to begin with !  )  . 

First uninstall any existing versions of dart-sass installed in your repository. 

And then, 

`npm install -g sass@1.26.3` , say . 

And then verify the path of sass installed by `which sass`  

You can that path in sassBinPath so this can be set globally for multiple projects .
